language: node_js
node_js: '5'
script: npm test
before_script:
- npm install
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
deploy:
- provider: s3
  access_key_id: AKIAJ2GK3I2HQMCYDZ2Q
  secret_access_key: &1
    secure: Jp9QEgrIM4mRvLqZ7cUT9hHoMusQ7bCDeI8LS4ylYMQr1zVHlPtxzUzQIformox70EzzD7LxJPvVRNMFBKZyZgoLpDLutEV9kBIquZsams6teQ1L1d2HlkdFcOSALhwK1wJ2roJiq43xjp544OQbWUc1nERA9gXYjny1CQK9obdgwsonfYSPmAU/Y2K9aBF+L2tAx7f5rAVvuKF00ZRtz5WMUppVD2xy9MJkCWmLSwQK+nYXXLRdNOGoNxqlBeRdioXpkWR9wCGFOzHNMZKGW5FRy8JZ3nP98HkCqTV1m9zDlhqUl0q/EV7CibAoDm9yXJJzGuvtw5m3WslAQYQCnaA1q3yRNIBK6PizqyjJ9WI2TixpLzTfGoGuaUkGViDZvDhSIAShT6mdQ2hnSYKUEYdLg1DixNOZ5X2Syi9caFWf+Q5uMS4Aki7jwRB0Ez+wes5IW4h3Cytm722daa3S11dHlxEfnv9NXZ5JO+6iQLWa6s/GecKNm97/UgIE8wKyYNLACi76SrheH+/o0i+X0xfpGoU3UZvpQew0d7+UquWT4XITQx6tIXljuUR6vGAnE2f4cclKMt+qUh8aNTzmnInfTB8N0bt4T0Gy6fs36JXQ8yx7sHP/WoMzzyDudtNVkuLCLFGIoB0kyUwAxSUYoA4WetCaKWHkiTwPF5FpyIQ=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: sirmosca/DraftBuddyWeb
  bucket: draftbuddyweb
- provider: codedeploy
  access_key_id: AKIAJ2GK3I2HQMCYDZ2Q
  secret_access_key: *1
  bucket: draftbuddyweb
  key: dbw
  bundle_type: none
  application: DraftBuddyWeb
  deployment_group: DraftBuddyWeb-DepGrp
  on: *2
before_deploy:
- mkdir -p dpl_cd_upload
- mv appspec.yml dpl_cd_upload/dbw
