language: node_js
node_js: '5'
script: npm test
before_script:
- npm install
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- zip -r latest *
- mkdir -p dpl_cd_upload
- gem update json
- pwd
#- mv latest.zip dpl_cd_upload/latest.zip
before_deploy:
- mkdir -p dpl_cd_upload
#- mv latest.zip dpl_cd_upload/latest.zip
- pwd
deploy:
- provider: s3
  access_key_id: AKIAIE63JXSXF6EGO4PA
  secret_access_key: &1
    secure: dGrSzBNlPacRtlpx8KEkDx/HzHMSQYgyJ8ekyyJp994WRPmFRBvKTFOTs1y1pDUioD/lVQ4z+zbLtTJujzVkGRaSH8Vc00GToZOEUh6HJF95prdga4k1Do13yfOwNUOL3X/9Eeauzgwob1hI67oF18EgUQJpAWLI2RXLjD82Mkz4o/kALeL9hR4wKHGLynYGKXfMRBh95FLXNz/2+q9iRo5eIjfXA5DCSyNgoz81ryO+RAVoA9ek3jbyuu6Of72hilPHJaPhJYncPAFQSSkhgKNKv4UuupFOl8SJaJjqTTay/OzAMTXaU13PeAIPiG9qlpy7oOEYMyx6vJBV+vZ2QgD5URoYor2LIGE3v84yagdFJLpP8+umscBZd1FIJ2Fy4lWiyur5QskOulWfG/mxWoTac3FQl4ovL8ebkP5Lsd1PACRP+hdPzGw+p5NqBYkjA2zSFf6OuPkgr3pElJj+zTWqSupYYRevNyqFr2XUnuwLWpDlg3ctuUv/3NUXxrtBTkKgCzRQjs+4eGTTJiltUkjNlt4MxU1A9LgVQ6NX5fSdOxyQ9beUuyMgX9KrZIhvbb1F874KVWl/ogDiFgExQke1cVXlQWBxR40DPqzEvqN4mWcktEIGS5gewFuCi22VTwBsT+fInF7SUeFbMmgkbCsTisnNmNKYO9npK8OiGGk=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: sirmosca/DraftBuddyWeb
  bucket: draftbuddyweb1
- provider: codedeploy
  access_key_id: AKIAIE63JXSXF6EGO4PA
  secret_access_key: *1
  bucket: draftbuddyweb1
  key: latest.zip
  bundle_type: zip
  application: DraftBuddyWeb
  deployment_group: DraftBuddyWeb-DepGrp
  on: *2
