language: node_js
node_js: '5'
script: npm test
before_script:
- npm install
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
deploy:
- provider: s3
  access_key_id: AKIAJ2GK3I2HQMCYDZ2Q
  secret_access_key: &1
    secure: Roqn6e21I7iwvoxMmE+5KalRz0E3ufFykF5eB8f0ZdBiC7hcDPO80Hx9/9cukWd4WBiVegG4fyQepT6F54Ov34zYbUQ/fv2tEsBKJRifOOLxlkOBl5IIAvaJ306UOJxb5PaFhB2I0umpzgDAwQX6rSe1rOiVpKSLk53Aysd0EzCFb7Iywmb86HONmA+yqFGLtp9Wq0x+i+TyzlwsyxmW5DgVycTcAyNPUBHfAHE3pGSw+Hjknu1u4DeQSwT+AqPhMZdKa9qPZx3LvJZe2WVC3KVcWmUa0+q90DpVsgZa2mKFa7n2Y9uQgV/K1bltMFh0sfTNWuubNh9XdnvyvRRwsQrupO8YKOzAFnKhfAPeXwznbQFRkHKh8o6seEovlczpsMYI/LMEz/7eXWJLRs8LwZ5tAsFkE92E18PIWnKZHKE6cb8Hnvnqx5j1lBOmQoNXIKKcu8wKNPPdc0aSJkqxoVKm3PkawVjGJk9TjKVlq5A/XFsMiEQQ1FDudfNBwLaHpAf6LTHgV7xUUy0gjTcYcEf/MFoTn/ghEiDDjBeulIInz591iVxxnOkS0e9qaChD5C+YmsAdTQhLEHvr7HaSASM81/yJXMl9YB+QL4xvX7IjDSiCw3B90ERppvHjVyB6PlV6h/h550gEQfkrK8G064OihJuInFTHHcQzUpy3iVU=
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: sirmosca/DraftBuddyWeb
  bucket: draftbuddyweb1
- provider: codedeploy
  access_key_id: AKIAJ2GK3I2HQMCYDZ2Q
  secret_access_key: *1
  bucket: draftbuddyweb1
  key: dbw
  bundle_type: zip
  application: DraftBuddyWeb
  deployment_group: DraftBuddyWeb-DepGrp
  on: *2
before_deploy:
- mkdir -p dpl_cd_upload
#- mv appspec.yml dpl_cd_upload/dbw
