language: node_js
node_js: '5'
script: echo "do it ---------------------->" && true
before_script:
- npm install
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- zip -r latest *
- mkdir -p dpl_cd_upload
- mv latest.zip dpl_cd_upload/latest.zip
script: npm test
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: &1
      secure: $AWS_SECRET_KEY
    local_dir: dpl_cd_upload
    skip_cleanup: true
    revision_type: github
    on: &2
      repo: github.com/sirmosca/DraftBuddyWeb
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: *1
    revision_type: github
    key: latest.zip
    bundle_type: zip
    application: DraftBuddyWeb-App
    deployment_group: DraftBuddyWeb-DepGrp